steps:
  - label: 'Build image'
    command: docker build --tag diagrams:2.0 -f ./docker/dev/Dockerfile .

  - wait
  - label: 'Build dist image and publish'
    command: docker build --tag diagrams-build:2.0 -f ./docker/dev/Dockerfile2 .